import React from 'react';
import { Col, Container, Row } from "react-bootstrap";
import {FooterPolicy} from '../components';
import "../styles.css";


const TermsAndConditions = () => {
  return (
    <div>
      <h1 className="page-header">Terms and Conditions</h1>
      <Container>
        <Row>
          <Col md={10}>
            <b>Acceptance of Terms:</b>
            <br /> <br /> This document is an electronic record in terms of
            Information Technology Act, 2000 and rules there under as applicable
            and the amended provisions pertaining to electronic records in
            various statutes as amended by the Information Technology Act, 2000.
            This electronic record is generated by a computer system and does
            not require any physical or digital signatures. This document is
            published in accordance with the provisions of Rule 3 (1) of the
            Information Technology (Intermediaries guidelines) Rules, 2011 that
            require publishing the rules and regulations, privacy policy and
            Terms of Use for access or usage of domain name
            [www.technocomputers.org.in] (“Website”), including the related
            mobile site and mobile application (hereinafter referred to as
            “Platform”) The Platform is owned by technocomputers. Your use of
            the Platform and services and tools are governed by the following
            terms and conditions ("Terms of Use") as applicable to the Platform
            including the applicable policies which are incorporated herein by
            way of reference. If You transact on the Platform, You shall be
            subject to the policies that are applicable to the Platform for such
            transaction. By mere use of the Platform, You shall be contracting
            with technocomputers Internet Private Limited and these terms and
            conditions including the policies constitute Your binding
            obligations, with technocomputers. For the purpose of these Terms of
            Use, wherever the context so requires "You" or "User" shall mean any
            natural or legal person who has agreed to become a buyer on the
            Platform by providing Registration Data while registering on the
            Platform as Registered User using the computer systems.
            technocomputers allows the User to surf the Platform or making
            purchases without registering on the Platform. ACCESSING, BROWSING
            OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE
            TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE
            TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly
            accepting these Terms of Use, You also accept and agree to be bound
            by technocomputers Policies (including but not limited to Privacy
            Policy available at Privacy) as amended from time to time.
          </Col>
        </Row>
      </Container>
      <div className="custom-fixed-bottom" style={{position:'fixed'}}>
        <FooterPolicy />
      </div>
    </div>
  );
}

export default TermsAndConditions;